name: Run tests

on:
    pull_request:
        branches: ["master"]
    push:
        branches: ["master"]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-python@v3
              with:
                python-version: 3.12

            - name: Install Dependencies
              run: pip install -e '.[dev]'
            - name: Run tests
              run: pytest --cov src/ --cov-report json

            - name: Update Coverage Badge
              # GitHub actions: default branch variable
              # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
              if: github.ref == 'refs/heads/master'
              uses: we-cli/coverage-badge-action@main
