name: Run tests

on:
    pull_request:
        branches: ["master"]
    push:
        branches: ["master"]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-python@v3
              with:
                python-version: 3.12

            - name: Install Dependencies
              run: pip install -e '.[dev]'
            - name: Run tests
              run: pytest
